name: dashboard_example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animations: ^2.0.11
  flutter_quill: ^11.0.0
  go_router: ^14.8.1
  auto_size_text: ^3.0.0
  permission_handler: ^11.4.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  flutter_bloc: ^9.0.0
  flutter_svg: ^2.0.17
  mobile_scanner: ^6.0.6
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Hacen-Bold.ttf
        - asset: assets/fonts/Hacen-Lt.ttf
        - asset: assets/fonts/Hacen.ttf

  assets:
    - assets/images/
  
