// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAclCQ1LNxL_bDodbE8sMa5PC4_zXwUJHg',
    appId: '1:472797098129:web:70cbe630ddd0bcd8500f30',
    messagingSenderId: '472797098129',
    projectId: 'moulink',
    authDomain: 'moulink.firebaseapp.com',
    databaseURL: 'https://moulink-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'moulink.appspot.com',
    measurementId: 'G-6XJZ3K4N7F',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAclCQ1LNxL_bDodbE8sMa5PC4_zXwUJHg',
    appId: '1:472797098129:web:1966d34817d81435500f30',
    messagingSenderId: '472797098129',
    projectId: 'moulink',
    authDomain: 'moulink.firebaseapp.com',
    databaseURL: 'https://moulink-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'moulink.appspot.com',
    measurementId: 'G-76PM1TP8W0',
  );

}